customers/urls.py
from django.urls import path

from customers import views


app_name = "customers"

urlpatterns = [
    path('', views.index, name="index"),
    path('account/', views.account, name="account"),

    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),

    path('menu/', views.menu, name="menu"),
    path('cart/', views.cart, name="cart"),
    path('cart/add/<int:id>/', views.cart_add, name="cart_add"),
    path('cart/update/<int:id>/', views.cart_update, name="cart_update"),
    path('cart/remove/<int:id>/', views.cart_remove, name="cart_remove"),

    path('cart/update/page/<int:id>/', views.cart_update_page, name="cart_update_page"),
    path('cart/remove/page/<int:id>/', views.cart_remove_page, name="cart_remove_page"),
    path('order/place/', views.order_place, name="order_place"),

]

managers/urls.py
from django.urls import path

from managers import views


app_name = "managers"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),

    path('category/', views.category, name="category"),
    path('category/add/', views.category_add, name="category_add"),
    path('category/edit/<int:id>/', views.category_edit, name="category_edit"),
    path('category/delete/<int:id>/', views.category_delete, name="category_delete"),

    path('products/', views.products, name="products"),
    path('products/add/', views.products_add, name="products_add"),
    path('products/edit/<int:id>/', views.products_edit, name="products_edit"),
    path('products/delete/<int:id>/', views.products_delete, name="products_delete"),
    path('products/stock/<int:id>/', views.products_stock, name="products_stock"),
    path('products/out/<int:id>/', views.products_out, name="products_out"),

    path('customers/', views.customers, name="customers"),

    path('orders/', views.orders, name="orders"),
    path('orders/packed/<int:id>/', views.orders_packed, name="orders_packed"),
    path('orders/shipped/<int:id>/', views.orders_shipped, name="orders_packed"),
    path('orders/delivered/<int:id>/', views.orders_delivered, name="orders_delivered"),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("customers.urls", namespace="customers")),
    path('manager/',include("managers.urls", namespace="managers")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

customers/models.py
from django.db import models

from users.models import User
from managers.models import Product


ORDER_STATUS_CHOICES = (
    ("pending","Pending"),
    ("packed","Packed"),
    ("shipped","Shipped"),
    ("delivered","Delivered"),
)


class Customer(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'customer_customer'
        verbose_name = 'customer'
        verbose_name_plural = 'customers'
        ordering = ["-id"]

    def __str__(self):
        return self.user.username
    


class OrderItem(models.Model):
    created_date = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    qty = models.IntegerField(default=1)
    amount = models.FloatField()


    class Meta:
        db_table = 'customer_order_cart'
        verbose_name = 'order cart'
        verbose_name_plural = 'order carts'
        ordering = ('id',)

    def __str__(self):

        return self.product.name
    


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem, related_name='items')
    address = models.TextField()
    pincode = models.IntegerField()
    amount = models.FloatField()
    status = models.CharField(max_length=25, choices=ORDER_STATUS_CHOICES)
    is_paid=models.BooleanField(default=False)


    class Meta:
        db_table = 'customer_order'
        verbose_name = 'order'
        verbose_name_plural = 'orders'
        ordering = ["-id"]

    def __str__(self):
        return self.customer.user.first_name

managers/models.py
from django.db import models

from users.models import User


class Manager(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'manager_manager'
        verbose_name = 'manager'
        verbose_name_plural = 'managers'
        ordering = ["-id"]

    def __str__(self):
        return self.user.username
    

class Category(models.Model):
    name=models.CharField(max_length=25)
    image=models.ImageField(upload_to="category")

    class Meta:
        db_table = 'manager_category'
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ["-id"]

    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.CharField(max_length=25)
    description=models.TextField()
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    price=models.FloatField()
    image=models.ImageField(upload_to="products")
    is_stock=models.BooleanField(default=True)


    class Meta:
        db_table = 'manager_product'
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ["-id"]

    def __str__(self):
        return self.name

customers/forms.py
from django import forms

from .models import Order
from users.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","username","password","email","phone_number"]

        widgets = {
            "first_name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Full name"}),
            "username":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Username"}),
            "phone_number":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Phone Number"}),
            "password":forms.widgets.PasswordInput(attrs={"class": "form-control","placeholder":"Password"}),
            "email":forms.widgets.EmailInput(attrs={"class": "form-control","placeholder":"Email"}),
        }



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["address","pincode"]

        widgets = {
            "address":forms.widgets.Textarea(attrs={"placeholder":"Address", "class": "border rounded-xl block w-full mb-4 py-2 px-5"}),
            "pincode":forms.widgets.NumberInput(attrs={"placeholder":"pincode", "class": "border rounded-xl block w-full mb-4 py-2 px-5"}),
        }

managers/forms.py
from django import forms

from .models import Category, Product


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name","image"]

        widgets = {
            "name":forms.widgets.TextInput(attrs={"placeholder":"Category Name","class":"form-control"}),
            "image":forms.widgets.FileInput(attrs={"class":"form-control"}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "category", "price", "description","image"]

        widgets = {
            "name":forms.widgets.TextInput(attrs={"placeholder":"Product Name","class":"form-control"}),
            "category":forms.widgets.Select(attrs={"class":"form-control"}),
            "price":forms.widgets.NumberInput(attrs={"placeholder":"Product Price","class":"form-control"}),
            "description":forms.widgets.Textarea(attrs={"placeholder":"Product Description","class":"form-control"}),
            "image":forms.widgets.FileInput(attrs={"class":"form-control"}),
        }

customers/views.py
from django.shortcuts import get_object_or_404, render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect

from django.db.models import Sum

from main.functions import generate_form_errors
from main.decorators import allow_customer

from managers.models import Manager, Category, Product
from customers.models import Customer, Order, OrderItem
from .forms import OrderForm, UserForm
from users.models import User


@login_required(login_url="/login/")
@allow_customer
def index(request):
    user=request.user
    categories = Category.objects.all()
    products = Product.objects.all()
    count = OrderItem.objects.filter(user=user, ordered=False).count()
    context = {
        "title": "EVA Restuarant Home",
        "categories": categories,
        "products": products,
        "count": count,
    }
    return render(request, 'customer/index.html', context=context)


@login_required(login_url="/login/")
@allow_customer
def account(request):
    user=request.user
    customer=Customer.objects.get(user=user)
    orders_count = Order.objects.filter(customer=customer).count()
    instances = Order.objects.filter(customer=customer)
    count = OrderItem.objects.filter(user=user, ordered=False).count()

    context = {
        "title": "EVA Restuarant Account",
        "user": user,
        "customer": customer,
        "orders_count": orders_count,
        "instances": instances,
        "count": count,
    }
    return render(request, 'customer/account.html', context=context)


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_customer:
                auth_login(request, user)

                return HttpResponseRedirect(reverse("customers:index"))
            else:
                context= {
                    "title": "Customer Login",
                    "error": True,
                    "message": "Invalid credentials or not allowed user"
                }
                return render(request, "customer/login.html", context=context)
        else:
            context= {
                "title": "Customer Login",
                "error": True,
                "message": "Invalid credentials or not allowed user"
            }
            return render(request, "customer/login.html", context=context)
    else:
        context= {
            "title" : "Manager Login"
        }
        return render(request, "customer/login.html", context=context)


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username = instance.username,
                password = instance.password,
                email = instance.email,
                first_name = instance.first_name,
                phone_number = instance.phone_number,
                is_customer=True
            )

            customer = Customer.objects.create(
                user=user,
            )
            customer.save()

            user.save()

            return HttpResponseRedirect(reverse("customers:login"))
        else:
            message = generate_form_errors(form)
            form = UserForm()
            context= {
                "title": "Customer Register",
                "error": True,
                "message": message,
                "form": form,
            }
            return render(request, "customer/register.html", context=context)

    else:
        form = UserForm()
        context= {
            "title": "Customer. Register",
            "form": form,
        }
        return render(request, "customer/register.html", context=context)




def logout(request):
    auth_logout(request)

    return HttpResponseRedirect(reverse("customers:login"))


@login_required(login_url="/login/")
@allow_customer
def menu(request):
    user=request.user
    customer=Customer.objects.get(user=user)
    categories = Category.objects.all()
    products = Product.objects.all()
    count = OrderItem.objects.filter(user=user, ordered=False).count()
    context = {
        "title": "EVA Restuarant Home",
        "categories": categories,
        "products": products,
        "count": count,
    }
    return render(request, 'customer/menu.html', context=context)


@login_required(login_url="/login/")
@allow_customer
def cart(request):
    user=request.user
    customer=Customer.objects.get(user=user)
    instances = OrderItem.objects.filter(user=user, ordered=False)
    count = OrderItem.objects.filter(user=user, ordered=False).count()
    context = {
        "title": "EVA Restuarant Home",
        "customer": customer,
        "instances": instances,
        "count": count,
    }
    return render(request, 'customer/cart.html', context=context)


@login_required(login_url="/login/")
@allow_customer
def cart_add(request,id):
    user=request.user
    customer=Customer.objects.get(user=user)
    product = Product.objects.get(id=id)
    cart = OrderItem.objects.create(
        user=user,
        product=product,
        amount=product.price,
        qty=1,
        ordered=False,
    )
    cart.save()

    return HttpResponseRedirect(reverse("customers:menu"))


@login_required(login_url="/login/")
@allow_customer
def cart_update(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount + cart.product.price
    cart.qty += 1
    cart.save()
    return HttpResponseRedirect(reverse("customers:menu"))


@login_required(login_url="/login/")
@allow_customer
def cart_remove(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount - cart.product.price
    cart.qty -= 1
    cart.save()

    if cart.qty == 0:
        cart.delete()

    return HttpResponseRedirect(reverse("customers:menu"))


@login_required(login_url="/login/")
@allow_customer
def cart_update_page(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount + cart.product.price
    cart.qty += 1
    cart.save()
    return HttpResponseRedirect(reverse("customers:cart"))


@login_required(login_url="/login/")
@allow_customer
def cart_remove_page(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount - cart.product.price
    cart.qty -= 1
    cart.save()

    if cart.qty == 0:
        cart.delete()

    return HttpResponseRedirect(reverse("customers:cart"))



@login_required(login_url="/login/")
@allow_customer
def order_place(request):
    user= request.user
    customer = Customer.objects.get(user=user)
    carts = OrderItem.objects.filter(user=user, ordered=False)
    total_amount = carts.aggregate(Sum("amount"))["amount__sum"]
    count = OrderItem.objects.filter(user=user, ordered=False).count()

    if request.method == "POST":

        form = OrderForm(request.POST, request.FILES)
        if form.is_valid():
            instance= form.save(commit=False)
            instance.amount=total_amount
            instance.customer = customer
            instance.status= 'pending'
            instance.save()

            for cart in carts:
                instance.items.add(cart)
                cart.ordered=True
                cart.save()
            
            return HttpResponseRedirect(reverse("customers:account"))
        else:
            form = OrderForm()
            context = {
                "title": "EVA Restuarant Edit Product",
                "error": True,
                "message": "Something went wrong",
                "carts":carts,
                "user":user,
                "total_amount":total_amount,
                "form":form,
                "count":count,
            }
            return render(request, "customer/order-place.html", context=context)
    
    else:
        form = OrderForm()
        context= {
            "title": "Canteen | Menu",
            "carts":carts,
            "user":user,
            "total_amount":total_amount,
            "form":form,
            "count":count,
        }
        return render(request, "customer/order-place.html", context=context)

templates/manager/add-category.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}
{% include 'includes/manager-nav.html' %}

<section class="p-10">
    <h1 class="font-bold text-2xl mb-6 text-center text-gray-700">ADD CATEGORY</h1>
    
    <div class="w-full sm:w-[70%] md:w-[50%] mx-auto">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <label for="categoryName" class="text-lg text-gray-500 font-normal">Category Name:</label>
            <div class="w-full py-2 px-4 mb-4 border-2 rounded-md mt-2">
                {{form.name}}
            </div>
            
            <label for="categoryImage" class="text-lg text-gray-500 font-normal">Select Category Image:</label>
            <div class="w-full py-2 px-4 mb-4 border-2 rounded-md mt-2">
                {{form.image}}
            </div>
            
            <div class="w-full py-2 px-4 mb-4 rounded-md flex justify-center items-center">
                <button type="submit" class="bg-gradient-to-r from-purple-500 to-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
            </div>
        </form>
    </div>
</section>


{% endblock %}

templates/manager/add-product.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}
{% include 'includes/manager-nav.html' %}
<section class="p-10 ">
    <h1 class="font-bold text-2xl mb-6 text-center text-gray-700">ADD ITEM</h1>
    <div class="w-full sm:w-[70%] md:w-[50%] m-auto">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="w-full py-1 px-5 mb-2 border-2 rounded-md">
                {{form.name}}
            </div>
            <label for="categoryName" class="text-lg text-gray-500 font-normal">Select Category</label>
            <div class="w-full py-1 px-5 mb-2 border-2 rounded-md mt-2">
                {{form.category}}
            </div>
            <div class="w-full py-1 px-5 mb-2 border-2 rounded-md">
                {{form.price}}
            </div>
            <div class="w-full py-1 px-5 mb-2 border-2 rounded-md">
                {{form.description}}
            </div>
            <label for="categoryName" class="text-lg text-gray-500 font-normal">Select Image</label>
            <div class="w-full py-1 px-5 mb-2 mt-2 border-2 rounded-md">
                {{form.image}}
            </div>
            <div class="w-full py-1 px-5 mb-2  rounded-md flex justify-center items-center ">
                <button type="submit" class="bg-gradient-to-r from-purple-500 to-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
            </div>
        </form>
        
        
    </div>


</section>

{% endblock %}

templates/manager/add-size.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}
{% include 'includes/manager-nav.html' %}
<section class="p-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="font-bold">ADD Size</h1>
        <a href="{% url 'managers:size' %}" class="py-2 px-4 text-white font-bold text-[14px] bg-cyan-600 rounded-md">Size</a>
    </div>
    <div class="w-full sm:w-[70%] md:w-[50%] m-auto">
        <form action="" method="post">
            {% csrf_token %}
            <div class="w-full py-1 px-5 mb-2 border-2 rounded-md">
                {{form.size}}
            </div>
        </form>
        
        
    </div>


</section>

{% endblock %}

templates/manager/categories.html
{% extends "base/manager-base.html" %} 
{% block container %} 
{% load static %}
{% include 'includes/manager-nav.html' %}

<section class="p-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="font-bold text-2xl">CATEGORIES</h1>
        <a href="{% url 'managers:category_add' %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-indigo-600 to-blue-500 rounded-md">ADD NEW</a>
    </div>

    <div class="overflow-x-auto border rounded-md shadow-md">
        <table class="min-w-full text-left text-sm font-light border border-gray-300 rounded-md overflow-hidden">
            <thead class="bg-gradient-to-r from-blue-500 to-indigo-600 text-white">
                <tr>
                    <th scope="col" class="px-6 py-4">Image</th>
                    <th scope="col" class="px-6 py-4">Name</th>
                    <th scope="col" class="px-6 py-4">Edit</th>
                    <th scope="col" class="px-6 py-4">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for instance in instances %}
                    <tr class="border-b border-gray-300">
                        <td class="whitespace-nowrap px-6 py-4">
                            <img src="{{instance.image.url}}" alt="Category Image" class="w-[60px] h-[60px] rounded-md">
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.name}}</td>
                        <td class="whitespace-nowrap px-6 py-4">
                            <a href="{% url 'managers:category_edit' id=instance.id %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-green-400 to-green-500 rounded-md">EDIT</a>
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">
                            <a href="{% url 'managers:category_delete' id=instance.id %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-red-500 to-pink-500 rounded-md">DELETE</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

templates/manager/customers.html
{% extends "base/manager-base.html" %} 
{% block container %} 
{% load static %}
{% include 'includes/manager-nav.html' %}

<section class="p-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="font-bold text-2xl">CUSTOMERS</h1>
    </div>

    <div class="overflow-x-auto border rounded-md shadow-md">
        <table class="min-w-full text-left text-sm font-light border border-gray-300 rounded-md overflow-hidden">
            <thead class="bg-gradient-to-r from-blue-500 to-indigo-600 text-white">
                <tr>
                    <th scope="col" class="px-6 py-4">Full Name</th>
                    <th scope="col" class="px-6 py-4">Username</th>
                    <th scope="col" class="px-6 py-4">Email</th>
                    <th scope="col" class="px-6 py-4">Phone</th>
                </tr>
            </thead>
            <tbody>
                {% for instance in instances %}
                    <tr class="border-b border-gray-300">
                        <td class="whitespace-nowrap px-6 py-4">{{instance.user.first_name}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.user.username}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.user.email}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.user.phone_number}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

templates/manager/index.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}
{% include 'includes/manager-nav.html' %}

<section class="px-10 py-10 grid grid-cols-4 gap-5 text-white">

    <div class="col-span-1 p-5 border-2 rounded-md bg-gradient-to-r from-purple-500 to-blue-500">
        <h1 class="text-center font-bold text-[18px] mb-[16px]">ORDERS</h1>
        <p class="text-center font-bold text-[28px]">{{orders}}</p>
    </div>
    <div class="col-span-1 p-5 border-2 rounded-md bg-gradient-to-r from-purple-500 to-blue-500">
        <h1 class="text-center font-bold text-[18px] mb-[16px]">PRODUCTS</h1>
        <p class="text-center font-bold text-[28px]">{{products}}</p>
    </div>
    <div class="col-span-1 p-5 border-2 rounded-md bg-gradient-to-r from-purple-500 to-blue-500">
        <h1 class="text-center font-bold text-[18px] mb-[16px]">CATEGORIES</h1>
        <p class="text-center font-bold text-[28px]">{{categories}}</p>
    </div>
    <div class="col-span-1 p-5 border-2 rounded-md bg-gradient-to-r from-purple-500 to-blue-500">
        <h1 class="text-center font-bold text-[18px] mb-[16px]">CUSTOMERS</h1>
        <p class="text-center font-bold text-[28px]">{{customers}}</p>
    </div>

</section>

<section class="p-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="font-bold text-2xl">RECENT ORDERS</h1>
        <a href="{% url 'managers:orders' %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-cyan-600 to-blue-500 rounded-md">VIEW ALL</a>
    </div>

    <div class="overflow-x-auto border rounded-md shadow-md">
        <table class="min-w-full text-left text-sm font-light border border-gray-300 rounded-md overflow-hidden">
            <thead class="bg-gradient-to-r from-blue-500 to-indigo-600 text-white">
                <tr>
                    <th scope="col" class="px-6 py-4">Name And Address</th>
                    <th scope="col" class="px-6 py-4">Products</th>
                    <th scope="col" class="px-6 py-4">Total</th>
                </tr>
            </thead>
            <tbody>
                {% for instance in instances %}
                    <tr class="border-b border-gray-300">
                        <td class="whitespace-nowrap px-6 py-4">
                            {{instance.customer.user.first_name}} <br>
                            {{instance.address}} <br>
                            {{instance.pincode}}
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">
                            {% for item in instance.items.all %}
                            <p>{{item.product.name}} x {{item.qty}}</p>
                            {% endfor %}
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.amount}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>





{% endblock %}

templates/manager/login.html
{% extends "base/manager-base.html" %} 
{% block container %} 
{% load static %}

<section class="flex justify-center items-center min-h-screen px-10 bg-gradient-to-r from-teal-500 to-purple-600">
    <div class="w-full sm:w-[60%] md:w-[40%] p-8 rounded-md shadow-md border-2 bg-white">
        <h1 class="text-center font-bold mb-6 text-[24px] text-gray-800">ADMIN LOGIN</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Enter Username" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <input type="password" name="password" placeholder="Enter Password" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <button type="submit" class="bg-gradient-to-r from-teal-600 to-purple-600 hover:bg-purple-700 text-white w-full py-2 px-4 rounded-md border-2 transition duration-300">LOGIN</button>
        </form>
        {% if error %}
        <p class="mt-4 text-red-500">{{message}}</p>
        {% endif %}
        <p class="mt-4 text-gray-600">Customer <a href="{% url 'customers:login' %}" class="text-teal-500">Login</a></p>
    </div>
</section>

{% endblock %}

templates/manager/products.html
{% extends "base/manager-base.html" %} 
{% block container %} 
{% load static %}
{% include 'includes/manager-nav.html' %}

<section class="p-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="font-bold text-2xl">PRODUCTS</h1>
        <a href="{% url 'managers:products_add' %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-cyan-600 to-blue-500 rounded-md">ADD NEW</a>
    </div>

    <div class="overflow-x-auto border rounded-md shadow-md">
        <table class="min-w-full text-left text-sm font-light border border-gray-300 rounded-md overflow-hidden">
            <thead class="bg-gradient-to-r from-blue-500 to-indigo-600 text-white">
                <tr>
                    <th scope="col" class="px-6 py-4">Image</th>
                    <th scope="col" class="px-6 py-4">Name</th>
                    <th scope="col" class="px-6 py-4">Category</th>
                    <th scope="col" class="px-6 py-4">Price</th>
                    <th scope="col" class="px-6 py-4">Edit</th>
                    <th scope="col" class="px-6 py-4">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for instance in instances %}
                    <tr class="border-b border-gray-300">
                        <td class="whitespace-nowrap px-6 py-4">
                            <img src="{{instance.image.url}}" alt="Product Image" class="w-[70px]">
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.name}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.category.name}}</td>
                        <td class="whitespace-nowrap px-6 py-4">{{instance.price}}</td>
                        <td class="whitespace-nowrap px-6 py-4">
                            <a href="{% url 'managers:products_edit' id=instance.id %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-green-400 to-green-500 rounded-md">EDIT</a>
                        </td>
                        <td class="whitespace-nowrap px-6 py-4">
                            <a href="{% url 'managers:products_delete' id=instance.id %}" class="py-2 px-4 text-white font-bold text-sm bg-gradient-to-r from-red-500 to-pink-500 rounded-md">DELETE</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}