customers/urls.py
from django.urls import path

from customers import views


app_name = "customers"

urlpatterns = [
    path('', views.index, name="index"),
    path('account/', views.account, name="account"),

    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),

    path('menu/', views.menu, name="menu"),
    path('cart/', views.cart, name="cart"),
    path('cart/add/<int:id>/', views.cart_add, name="cart_add"),
    path('cart/update/<int:id>/', views.cart_update, name="cart_update"),
    path('cart/remove/<int:id>/', views.cart_remove, name="cart_remove"),

    path('cart/update/page/<int:id>/', views.cart_update_page, name="cart_update_page"),
    path('cart/remove/page/<int:id>/', views.cart_remove_page, name="cart_remove_page"),
    path('order/place/', views.order_place, name="order_place"),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("customers.urls", namespace="customers")),
    path('manager/',include("managers.urls", namespace="managers")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

customers/models.py
from django.db import models

from users.models import User
from managers.models import Product


ORDER_STATUS_CHOICES = (
    ("pending","Pending"),
    ("packed","Packed"),
    ("shipped","Shipped"),
    ("delivered","Delivered"),
)


class Customer(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'customer_customer'
        verbose_name = 'customer'
        verbose_name_plural = 'customers'
        ordering = ["-id"]

    def __str__(self):
        return self.user.username
    


class OrderItem(models.Model):
    created_date = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    qty = models.IntegerField(default=1)
    amount = models.FloatField()


    class Meta:
        db_table = 'customer_order_cart'
        verbose_name = 'order cart'
        verbose_name_plural = 'order carts'
        ordering = ('id',)

    def __str__(self):

        return self.product.name
    


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem, related_name='items')
    address = models.TextField()
    pincode = models.IntegerField()
    amount = models.FloatField()
    status = models.CharField(max_length=25, choices=ORDER_STATUS_CHOICES)
    is_paid=models.BooleanField(default=False)


    class Meta:
        db_table = 'customer_order'
        verbose_name = 'order'
        verbose_name_plural = 'orders'
        ordering = ["-id"]

    def __str__(self):
        return self.customer.user.first_name

customers/forms.py
from django import forms

from .models import Order
from users.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","username","password","email","phone_number"]

        widgets = {
            "first_name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Full name"}),
            "username":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Username"}),
            "phone_number":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Phone Number"}),
            "password":forms.widgets.PasswordInput(attrs={"class": "form-control","placeholder":"Password"}),
            "email":forms.widgets.EmailInput(attrs={"class": "form-control","placeholder":"Email"}),
        }



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["address","pincode"]

        widgets = {
            "address":forms.widgets.Textarea(attrs={"placeholder":"Address", "class": "border rounded-xl block w-full mb-4 py-2 px-5"}),
            "pincode":forms.widgets.NumberInput(attrs={"placeholder":"pincode", "class": "border rounded-xl block w-full mb-4 py-2 px-5"}),
        }

customers/views.py
from django.shortcuts import get_object_or_404, render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect

from django.db.models import Sum

from main.functions import generate_form_errors
from main.decorators import allow_customer

from managers.models import Manager, Category, Product
from customers.models import Customer, Order, OrderItem
from .forms import OrderForm, UserForm
from users.models import User


@login_required(login_url="/login/")
@allow_customer
def index(request):
    user=request.user
    categories = Category.objects.all()
    products = Product.objects.all()
    count = OrderItem.objects.filter(user=user, ordered=False).count()
    context = {
        "title": "EVA Restuarant Home",
        "categories": categories,
        "products": products,
        "count": count,
    }
    return render(request, 'customer/index.html', context=context)


@login_required(login_url="/login/")
@allow_customer
def account(request):
    user=request.user
    customer=Customer.objects.get(user=user)
    orders_count = Order.objects.filter(customer=customer).count()
    instances = Order.objects.filter(customer=customer)
    count = OrderItem.objects.filter(user=user, ordered=False).count()

    context = {
        "title": "EVA Restuarant Account",
        "user": user,
        "customer": customer,
        "orders_count": orders_count,
        "instances": instances,
        "count": count,
    }
    return render(request, 'customer/account.html', context=context)


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_customer:
                auth_login(request, user)

                return HttpResponseRedirect(reverse("customers:index"))
            else:
                context= {
                    "title": "Customer Login",
                    "error": True,
                    "message": "Invalid credentials or not allowed user"
                }
                return render(request, "customer/login.html", context=context)
        else:
            context= {
                "title": "Customer Login",
                "error": True,
                "message": "Invalid credentials or not allowed user"
            }
            return render(request, "customer/login.html", context=context)
    else:
        context= {
            "title" : "Manager Login"
        }
        return render(request, "customer/login.html", context=context)


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username = instance.username,
                password = instance.password,
                email = instance.email,
                first_name = instance.first_name,
                phone_number = instance.phone_number,
                is_customer=True
            )

            customer = Customer.objects.create(
                user=user,
            )
            customer.save()

            user.save()

            return HttpResponseRedirect(reverse("customers:login"))
        else:
            message = generate_form_errors(form)
            form = UserForm()
            context= {
                "title": "Customer Register",
                "error": True,
                "message": message,
                "form": form,
            }
            return render(request, "customer/register.html", context=context)

    else:
        form = UserForm()
        context= {
            "title": "Customer. Register",
            "form": form,
        }
        return render(request, "customer/register.html", context=context)




def logout(request):
    auth_logout(request)

    return HttpResponseRedirect(reverse("customers:login"))


@login_required(login_url="/login/")
@allow_customer
def menu(request):
    user=request.user
    customer=Customer.objects.get(user=user)
    categories = Category.objects.all()
    products = Product.objects.all()
    count = OrderItem.objects.filter(user=user, ordered=False).count()
    context = {
        "title": "EVA Restuarant Home",
        "categories": categories,
        "products": products,
        "count": count,
    }
    return render(request, 'customer/menu.html', context=context)


@login_required(login_url="/login/")
@allow_customer
def cart(request):
    user=request.user
    customer=Customer.objects.get(user=user)
    instances = OrderItem.objects.filter(user=user, ordered=False)
    count = OrderItem.objects.filter(user=user, ordered=False).count()
    context = {
        "title": "EVA Restuarant Home",
        "customer": customer,
        "instances": instances,
        "count": count,
    }
    return render(request, 'customer/cart.html', context=context)


@login_required(login_url="/login/")
@allow_customer
def cart_add(request,id):
    user=request.user
    customer=Customer.objects.get(user=user)
    product = Product.objects.get(id=id)
    cart = OrderItem.objects.create(
        user=user,
        product=product,
        amount=product.price,
        qty=1,
        ordered=False,
    )
    cart.save()

    return HttpResponseRedirect(reverse("customers:menu"))


@login_required(login_url="/login/")
@allow_customer
def cart_update(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount + cart.product.price
    cart.qty += 1
    cart.save()
    return HttpResponseRedirect(reverse("customers:menu"))


@login_required(login_url="/login/")
@allow_customer
def cart_remove(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount - cart.product.price
    cart.qty -= 1
    cart.save()

    if cart.qty == 0:
        cart.delete()

    return HttpResponseRedirect(reverse("customers:menu"))


@login_required(login_url="/login/")
@allow_customer
def cart_update_page(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount + cart.product.price
    cart.qty += 1
    cart.save()
    return HttpResponseRedirect(reverse("customers:cart"))


@login_required(login_url="/login/")
@allow_customer
def cart_remove_page(request,id):
    user=request.user
    cart = OrderItem.objects.get(id=id)
    cart.amount = cart.amount - cart.product.price
    cart.qty -= 1
    cart.save()

    if cart.qty == 0:
        cart.delete()

    return HttpResponseRedirect(reverse("customers:cart"))



@login_required(login_url="/login/")
@allow_customer
def order_place(request):
    user= request.user
    customer = Customer.objects.get(user=user)
    carts = OrderItem.objects.filter(user=user, ordered=False)
    total_amount = carts.aggregate(Sum("amount"))["amount__sum"]
    count = OrderItem.objects.filter(user=user, ordered=False).count()

    if request.method == "POST":

        form = OrderForm(request.POST, request.FILES)
        if form.is_valid():
            instance= form.save(commit=False)
            instance.amount=total_amount
            instance.customer = customer
            instance.status= 'pending'
            instance.save()

            for cart in carts:
                instance.items.add(cart)
                cart.ordered=True
                cart.save()
            
            return HttpResponseRedirect(reverse("customers:account"))
        else:
            form = OrderForm()
            context = {
                "title": "EVA Restuarant Edit Product",
                "error": True,
                "message": "Something went wrong",
                "carts":carts,
                "user":user,
                "total_amount":total_amount,
                "form":form,
                "count":count,
            }
            return render(request, "customer/order-place.html", context=context)
    
    else:
        form = OrderForm()
        context= {
            "title": "Canteen | Menu",
            "carts":carts,
            "user":user,
            "total_amount":total_amount,
            "form":form,
            "count":count,
        }
        return render(request, "customer/order-place.html", context=context)

templates/customer/account.html
{% extends "base/customer-base.html" %} 
{% block container %} 
{% load static %}
{% include 'includes/customer-nav.html' %}

<section class="grid grid-cols-4 gap-5 p-10">
    <div class="col-span-1 p-4 rounded-md border shadow-md bg-gradient-to-r from-teal-500 to-purple-600 text-white">
        <div class="flex justify-center mb-4">
            <img src="{% static 'images/man.png' %}" alt="profile" class="w-[60px] rounded-full">
        </div>
        <h1 class="text-center mb-4 font-bold text-lg">{{customer.user.first_name}}</h1>
        <h1 class="text-center mb-4 font-bold text-lg">{{customer.user.email}}</h1>
        <h1 class="text-center mb-4 font-bold text-lg">{{customer.user.phone_number}}</h1>
    </div>
    <div class="col-span-3 p-4 rounded-md border shadow-md">
        <h1 class="font-bold mb-4 text-2xl text-gradient">YOUR ORDERS</h1>
        <div class="grid grid-cols-3 gap-5">
            {% for order in instances %}
            <div class="col-span-1 p-4 rounded-md border shadow-md bg-gray-100">
                <h1 class="text-lg font-bold mb-2">Order ID - 00010{{order.id}}</h1>
                <p class="text-gray-600 mb-4">{{order.date_ordered}}</p>
                {% for item in order.items.all %}
                    <div class="flex items-center justify-between mb-2">
                        <p class="text-gray-700">{{item.product.name}} x {{item.qty}}</p>
                        <p class="text-gray-700">{{item.product.price}}</p>
                    </div>
                {% endfor %}
                <hr class="my-4 border-t border-gray-300">
                <div class="flex items-center justify-between">
                    <h1 class="text-lg font-bold">Total Amount</h1>
                    <h1 class="text-lg font-bold">{{order.amount}}</h1>
                </div>
                <p id="countdown" class="mt-4 font-bold text-green-600">Product will arrive in one hour</p>
                <div class="mt-8">
                    <h2 class="text-lg font-semibold mb-2">Feedback here</h2>
                </div>
                <textarea id="feedback" class="mt-2 p-3 border border-gray-300 rounded-md w-full h-20" placeholder="Leave your feedback here..."></textarea>
                <button id="submitFeedback" class="bg-teal-500 text-white font-bold py-2 px-4 rounded-full mt-4 hover:bg-teal-600">Submit Feedback</button>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<script>
    // JavaScript for handling feedback submission
    document.getElementById('submitFeedback').addEventListener('click', function() {
        // Submit feedback logic here
        // For demonstration purposes, showing an alert
        alert("Your feedback has been sent!");
        // Clear the text area
        document.getElementById('feedback').value = "";
    });
</script>

{% endblock %}

templates/customer/cart.html
{% extends "base/customer-base.html" %} {% block container %} {% load static %}
{% include 'includes/customer-nav.html' %}


<!-- Spotlight Section -->
<main class="container mx-auto py-10">
    <h2 class="text-3xl font-extrabold mb-8">Shopping Cart</h2>

    <!-- Cart Items -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {% if instances %}
        {% for instance in instances %}
        <div class="bg-white p-4 rounded-md shadow-md">
            <img src="{{instance.product.image.url}}" alt="Item Image" class="w-full h-[70%] object-cover mb-4 rounded-md">
            <h3 class="text-xl font-bold mb-2">{{instance.product.name}}</h3>
            <div class="flex justify-between items-center">
                <div class="flex items-center space-x-2">
                    <a href="{% url 'customers:cart_remove_page' id=instance.id %}" class="bg-gradient-to-r from-purple-500 to-blue-500 text-white px-3 py-1 rounded-full">-</a>
                    <span class="text-xl font-semibold">{{instance.qty}}</span>
                    <a href="{% url 'customers:cart_update_page' id=instance.id %}" class="bg-gradient-to-r from-purple-500 to-blue-500 text-white px-3 py-1 rounded-full">+</a>
                </div>
                <span class="text-xl font-semibold">₹ {{instance.amount}}</span>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Checkout Section -->
    <div class="mt-8 flex justify-end">
        <a href="{% url 'customers:order_place' %}" class="bg-gradient-to-r from-purple-500 to-blue-500 text-white px-6 py-3 rounded-md">Checkout</a>
    </div>
    {% else%}
    <h2 class="text-xl font-semibold text-gray-500 mb-8">No items found.</h2>
    {% endif %}

</main>



{% endblock %}

templates/customer/index.html
{% extends "base/customer-base.html" %} {% block container %} {% load static %}
{% include 'includes/customer-nav.html' %}


<!-- Spotlight Section -->
<section class="bg-gradient-to-r from-green-400 via-teal-500 to-blue-600 text-white py-16">
    <div class="container mx-auto text-center">
        <h1 class="text-4xl font-extrabold mb-4">Empowering your health with science and compassion</h1>
        <p class="text-lg mb-8">Where healing, care, and discovery meet</p>
        <a href="{% url 'customers:menu' %}" class="bg-white text-teal-500 hover:bg-teal-600 hover:text-white text-lg font-bold py-2 px-6 rounded-full transition duration-300">Explore Medicines</a>
    </div>
</section>

<!-- About Section -->
<section class="container mx-auto py-16">
    <div class="flex flex-col md:flex-row items-center justify-between">
        <div class="md:w-1/2 mr-5">
            <img src="{% static 'images/pharma.webp' %}" alt="About Eva Restaurant" class="rounded-lg ">
        </div>
        <div class="md:w-1/2 bg-white p-8 rounded-md shadow-md">
            <h2 class="text-3xl font-bold mb-4 text-gray-800">About Eva Pharma</h2>
            <p class="text-gray-700 mb-4"> Eva Pharma is a 24/7 online medicine delivery service that ensures medications are delivered within an hour of ordering. The website is user-friendly, allowing customers to easily upload prescriptions, which are verified by licensed pharmacists.</p>
            <p class="text-gray-700">Eva Pharma enhances access to necessary medications for everyone, particularly benefiting the elderly, disabled, and those in urgent need, thereby improving community health outcomes.</p>
            <div class="mt-8 flex items-center">
                <div class="bg-teal-500 text-white rounded-full p-2 mr-4">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7"></path>
                    </svg>
                </div>
                <p class="text-teal-500 font-semibold">
                    <a href="{% url 'customers:menu' %}">Explore Medicines</a>
                </p>
            </div>
        </div>
    </div>
</section>



<!-- Features Section -->
<section class="bg-gray-100 py-16">
    <div class="container mx-auto text-center">
        <h2 class="text-3xl font-extrabold mb-8">Key Features</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <!-- Feature 1 -->
            <div class="bg-white p-6 rounded-md shadow-md">
                <h3 class="text-xl font-bold mb-4">24/7 Availability</h3>
                <p class="text-gray-700">The website operates 24/7, allowing customers to order medications anytime, day or night, which is crucial for emergencies..</p>
            </div>
            <!-- Feature 2 -->
            <div class="bg-white p-6 rounded-md shadow-md">
                <h3 class="text-xl font-bold mb-4">One-hour Delivery</h3>
                <p class="text-gray-700">Swift delivery within an hour for local orders meets urgent medication needs, supported by a robust logistical network and efficient dispatch systems.</p>
            </div>
            <!-- Feature 3 -->
            <div class="bg-white p-6 rounded-md shadow-md">
                <h3 class="text-xl font-bold mb-4">Secure Payment</h3>
                <p class="text-gray-700">Multiple payment methods including credit/debit cards, digital wallets, and perhaps cash on delivery to accommodate all users.</p>
            </div>
        </div>
    </div>
</section>


{% include 'includes/customer-foot.html' %}

{% endblock %}

templates/customer/login.html
{% extends "base/customer-base.html" %} 
{% block container %} 
{% load static %}

<section class="flex justify-center items-center min-h-screen px-10 bg-gradient-to-r from-green-400 via-teal-500 to-blue-600">
    <div class="w-full sm:w-[60%] md:w-[40%] p-8 rounded-md shadow-md border-2 bg-white">
        <h1 class="text-center font-bold mb-6 text-[24px] text-gray-800">CUSTOMER LOGIN</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Enter Username" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <input type="password" name="password" placeholder="Enter Password" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <button type="submit" class="bg-gradient-to-r from-green-400 via-teal-500 to-blue-600 font-semibold text-white w-full py-2 px-4 rounded-md border-2 transition duration-300">LOGIN</button>
        </form>
        {% if error %}
        <p class="mt-4 text-red-500">{{message}}</p>
        {% endif %}
        <p class="mt-4 text-gray-600">Create an <a href="{% url 'customers:signup' %}" class="text-teal-500">Account</a></p>
        <p class="mt-4 text-gray-600">Manager <a href="{% url 'managers:login' %}" class="text-teal-500">Login</a></p>
    </div>
</section>

{% endblock %}

templates/customer/menu.html
{% extends "base/customer-base.html" %} 
{% block container %} 
{% load static %}
{% include 'includes/customer-nav.html' %}

<section class="bg-gradient-to-r from-teal-500 to-purple-600 text-white py-16">
    <div class="container mx-auto text-center">
        <h2 class="text-4xl font-extrabold mb-8">Explore Our Medicines</h2>
        <div class="flex justify-center space-x-4">
            {% for category in categories %}
            <!-- <a href="#" class="hover:underline">
                <img src="{{category.image.url}}" alt="Appetizers" class="ml-4 rounded-[10px] w-[100px] h-[90px]">
                <span class="block mt-2 font-semibold">{{category.name}}</span>
            </a> -->
            {% endfor %}
        </div>
    </div>
</section>

<!-- Prescription Upload Section -->
<section class="container mx-auto py-16">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <!-- Prescription Upload Card -->
     

        <!-- Product Cards -->
        {% for product in products %}
        <div class="bg-white p-6 rounded-md shadow-md">
            <img src="{{product.image.url}}" alt="Item 1" class="rounded-md mb-4">
            <h3 class="text-xl font-bold mb-2">{{product.name}}</h3>
            <p class="text-gray-700 mb-4">{{product.description}}</p>
            <p class="text-gray-800 font-semibold mb-4">₹ {{product.price}}</p>
            <a href="{% url 'customers:cart_add' id=product.id %}" class="bg-teal-500 text-white font-bold py-2 px-4 rounded-full mt-4 hover:bg-teal-600">Add to Cart</a>
        </div>
        {% endfor %}

    </div>
</section>

{% include 'includes/customer-foot.html' %}

<script>
    // JavaScript for file input change event
    document.getElementById('prescriptionFileInput').addEventListener('change', function(event) {
        const file = event.target.files[0];
        const preview = document.getElementById('prescriptionPreview');
        const uploadButton = document.getElementById('uploadButton');

        // Clear previous preview
        preview.innerHTML = '';

        // Create image element for preview
        const img = document.createElement('img');
        img.classList.add('rounded-md', 'mb-4');
        img.file = file;
        preview.appendChild(img);

        // Display preview image
        const reader = new FileReader();
        reader.onload = (function(aImg) {
            return function(e) {
                aImg.src = e.target.result;
                uploadButton.disabled = false; // Enable upload button after selecting image
            };
        })(img);
        reader.readAsDataURL(file);
    });
</script>

{% endblock %}

templates/customer/order-place.html
{% extends "base/customer-base.html" %} {% block container %} {% load static %}
{% include 'includes/customer-nav.html' %}

<section class="w-90% m-auto py-10 grid grid-cols-1 lg:grid-cols-2 gap-10">
    <!-- Cart Items and Bill Details -->
    <div class="bg-white p-8 rounded-md shadow-md mr-4">
        <h1 class="text-2xl font-bold mb-5">Your Cart</h1>
        
        <!-- Sample Cart Items -->
        <div class="mb-4">
            {% for cart in carts %}
            <div class="flex justify-between items-center mb-2">
                <span class="text-gray-500">{{cart.product.name}}</span>
                <span class="text-gray-500">₹ {{cart.product.price}}</span>
            </div>
            {% endfor %}
        </div>

        <!-- Bill Details -->
        <div class="border-t border-gray-300 pt-4">
            <div class="flex justify-between items-center mb-2">
                <span class="text-gray-500">Total Items:</span>
                <span class="text-gray-500">{{count}}</span>
            </div>
            <div class="flex justify-between items-center mb-2">
                <span class="text-gray-500 font-semibold text-[18px]">Total Amount:</span>
                <span class="text-gray-500 font-semibold text-[18px]">₹ {{total_amount}}</span>
            </div>
        </div>
    </div>

    <!-- Address and Pincode Form -->
    <div>
        <form action="" method="post" enctype="multipart/form-data" class="px-10">
            {% csrf_token %}
            
            <p class="font-bold mb-1">Enter your full address</p>
            {{form.address}}
            
            <p class="font-bold mb-1 mt-4">Enter your pincode</p>
            {{form.pincode}}

            <div class="text-center mt-8">
                <input type="submit" value="ORDER NOW" class="py-2 px-4 text-white font-bold text-[14px] bg-gradient-to-r from-purple-500 to-blue-500 rounded-md" />
            </div>
        </form>
    </div>
</section>





{% endblock %}

templates/customer/register.html
{% extends "base/customer-base.html" %} 
{% block container %} 
{% load static %}

<section class="flex justify-center items-center min-h-screen px-10 bg-gradient-to-r from-green-400 via-teal-500 to-blue-600">
    <div class="w-full sm:w-[60%] md:w-[40%] p-8 rounded-md shadow-md border-2 bg-white">
        <h1 class="text-center font-bold mb-6 text-[24px] text-gray-800">CREATE ACCOUNT</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="first_name" placeholder="Enter Name" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <input type="text" name="username" placeholder="Enter Username" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <input type="email" name="email" placeholder="Enter Email" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <input type="number" name="phone_number" placeholder="Enter Phone" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <input type="password" name="password" placeholder="Enter Password" class="outline-none w-full py-2 px-4 mb-4 rounded-md border-2 text-gray-700 focus:ring-teal-500 focus:border-teal-500">
            <button type="submit" class="bg-gradient-to-r from-green-400 via-teal-500 to-blue-600 hover:bg-purple-700 font-semibold text-white w-full py-2 px-4 rounded-md border-2 transition duration-300">LOGIN</button>
        </form>
        {% if error %}
        <p class="mt-4 text-red-500">{{message}}</p>
        {% endif %}
        <p class="mt-4 text-gray-600">Existing <a href="{% url 'customers:login' %}" class="text-teal-500">Account</a></p>
        <p class="mt-4 text-gray-600">Manager <a href="{% url 'managers:login' %}" class="text-teal-500">Login</a></p>
    </div>
</section>

{% endblock %}