customers/urls.py
from django.urls import path

from customers import views


app_name = "customers"

urlpatterns = [
    path('', views.index, name="index"),
    path('account/', views.account, name="account"),

    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),

    path('menu/', views.menu, name="menu"),
    path('cart/', views.cart, name="cart"),
    path('cart/add/<int:id>/', views.cart_add, name="cart_add"),
    path('cart/update/<int:id>/', views.cart_update, name="cart_update"),
    path('cart/remove/<int:id>/', views.cart_remove, name="cart_remove"),

    path('cart/update/page/<int:id>/', views.cart_update_page, name="cart_update_page"),
    path('cart/remove/page/<int:id>/', views.cart_remove_page, name="cart_remove_page"),
    path('order/place/', views.order_place, name="order_place"),

]

managers/urls.py
from django.urls import path

from managers import views


app_name = "managers"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),

    path('category/', views.category, name="category"),
    path('category/add/', views.category_add, name="category_add"),
    path('category/edit/<int:id>/', views.category_edit, name="category_edit"),
    path('category/delete/<int:id>/', views.category_delete, name="category_delete"),

    path('products/', views.products, name="products"),
    path('products/add/', views.products_add, name="products_add"),
    path('products/edit/<int:id>/', views.products_edit, name="products_edit"),
    path('products/delete/<int:id>/', views.products_delete, name="products_delete"),
    path('products/stock/<int:id>/', views.products_stock, name="products_stock"),
    path('products/out/<int:id>/', views.products_out, name="products_out"),

    path('customers/', views.customers, name="customers"),

    path('orders/', views.orders, name="orders"),
    path('orders/packed/<int:id>/', views.orders_packed, name="orders_packed"),
    path('orders/shipped/<int:id>/', views.orders_shipped, name="orders_packed"),
    path('orders/delivered/<int:id>/', views.orders_delivered, name="orders_delivered"),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("customers.urls", namespace="customers")),
    path('manager/',include("managers.urls", namespace="managers")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

templates/includes/customer-foot.html
{% load static %}

<footer class="bg-gradient-to-r from-green-400 via-teal-500 to-blue-600 text-white py-8">
    <div class="container mx-auto text-center">
        <p>&copy; 2024 Eva Pharma. All rights reserved.</p>
    </div>
</footer>

templates/includes/customer-nav.html
{% load static %}


<header class="h-[70px] flex justify-between items-center px-10 shadow-md bg-gradient-to-r from-green-400 via-teal-500 to-blue-600">
    <div>
        <h1 class="font-extrabold text-[24px] text-white">EVA PHARMA</h1>
    </div>
    <div class="flex items-center">
        <ul class="flex justify-end items-center">
            <li class="mr-8 font-semibold text-[18px] text-white"><a href="{% url 'customers:index' %}">Home</a></li>
            <li class="mr-8 font-semibold text-[18px] text-white"><a href="{% url 'customers:menu' %}">Medicine</a></li>
            <li class="mr-8 font-semibold text-[18px] text-white"><a href="{% url 'customers:account' %}">Account</a></li>
            
            <!-- Cart Option with Shopping Bag Icon -->
            <li class="relative mr-[50px]">
                <a href="{% url 'customers:cart' %}" class="flex items-center text-white">
                    <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7a3 3 0 100-6 3 3 0 000 6zM21 21a1 1 0 01-1 1H4a1 1 0 01-1-1M4 19h16v-8H4a2 2 0 00-2 2v4a2 2 0 002 2z"></path>
                    </svg>
                    <!-- Rounded Badge for Item Count -->
                    <div class="bg-white text-teal-500 w-6 h-6 rounded-full flex items-center justify-center absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2">
                        <span class="text-xs font-semibold">{{count}}</span>
                    </div>
                </a>
            </li>

            <!-- Logout Option -->
            <li class="mr-8 font-semibold text-[18px] py-2 px-4 border-white border-[3px] rounded-md text-white"><a href="{% url 'customers:logout' %}">LOGOUT</a></li>
        </ul>
    </div>
</header>

templates/includes/manager-nav.html
{% load static %}


<header class="h-[70px] flex justify-between items-center px-10 shadow-md bg-gradient-to-r from-green-400 via-teal-500 to-blue-600 text-white">
    <div>
        <h1 class="font-extrabold text-[24px]">MANAGER</h1>
    </div>
    <div>
        <ul class="flex justify-end items-center">
            <li class="mr-8 font-semibold text-[16px]"><a href="{% url 'managers:index' %}" class="hover:underline">Home</a></li>
            <li class="mr-8 font-semibold text-[16px]"><a href="{% url 'managers:category' %}" class="hover:underline">Categories</a></li>
            <li class="mr-8 font-semibold text-[16px]"><a href="{% url 'managers:products' %}" class="hover:underline">Menu</a></li>
            <li class="mr-8 font-semibold text-[16px]"><a href="{% url 'managers:orders' %}" class="hover:underline">Orders</a></li>
            <li class="mr-8 font-semibold text-[16px]"><a href="{% url 'managers:customers' %}" class="hover:underline">Customers</a></li>
            <li class="mr-8 font-semibold text-[16px] py-2 px-4 border-white border rounded-md"><a href="{% url 'managers:logout' %}" class="hover:underline">LOGOUT</a></li>
        </ul>
    </div>
</header>